# nixpacks.toml
[phases.setup]
nixPkgs = ['bun']

[phases.install]
cmds = ['bun install']

[phases.build]
cmds = ['echo "Build phase completed"']

[start]
cmd = 'bun run start:http'

[variables]
NODE_ENV = 'production'